services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=webstore'
      - 'POSTGRES_PASSWORD=boot'
      - 'POSTGRES_USER=spring'
    ports:
      - '5432'
    networks:
      - backend

  liquibase:
    image: 'liquibase:latest'
    environment:
      - 'changeLogFile=db/changelog/db.changelog-master.xml'
      - 'url=jdbc:postgresql://localhost/webstore'
      - 'username=springuser'
      - 'password=boot'
    networks:
      - backend
    depends_on:
      - postgres

networks:
  backend:
    driver: bridge
