#services:
#  postgres:
#    image: 'postgres:16-alpine'
#    environment:
#      - 'POSTGRES_DB=webstore'
#      - 'POSTGRES_PASSWORD=deme'
#      - 'POSTGRES_USER=postgres'
#    ports:
#      - '5432'
#
#  liquibase:
#    image: 'liquibase:latest'
#    environment:
#      - 'changeLogFile=db/changelog/db.changelog-master.xml'
#      - 'url=jdbc:postgresql://postgres:5432/webstore'
#      - 'username=springuser'
#      - 'password=boot'
#    depends_on:
#      - postgres