services:
  postgres:
    image: 'postgres:latest-alpine:3.20'
    environment:
      - 'POSTGRES_DB=webstore'
      - 'POSTGRES_PASSWORD=boot'
      - 'POSTGRES_USER=spring'
    ports:
      - '5432'

  liquibase:
    image: 'liquibase:latest-alpine'
    environment:
      - 'changeLogFile=db/changelog/db.changelog-master.xml'
      - 'url=jdbc:postgresql://localhost/webstore'
      - 'username=springuser'
      - 'password=boot'